# To execute this sample, please install ffmpeg.
import sys
import time
import math
import datetime
import GttsAIStreamer as gasr

# print sentence by a character incrementally.
def print_incremental(st, interval_sec):
  for i in range(len(st)):
    if not running:
      break
    print(f"{st[i]}", end='')
    sys.stdout.flush()
    interruptible_sleep(interval_sec)

# Customized sleep for making available of running flag interruption.
def interruptible_sleep(time_sec):
  counter = math.floor(time_sec / 0.01)
  frac = time_sec - (counter * 0.01)
  for i in range(counter):
    if not running:
      break
    time.sleep(0.01)
  if not running:
    return
  time.sleep(frac)

# callback for getting answer of ChatGPT
# The voice generated by GttsGenerator is given.
def answer_cb(user_message, completion, voice):
  print(f"\n[{user_message.extern.author.name} {user_message.extern.datetime}] {user_message.message}\n")
  time_str = datetime.datetime.now().strftime ('%H:%M:%S')
  message = completion.choices[0]["message"]["content"]

  # Play the voice by VoicePlayer of GttsAIStreamer
  # If you use Python launcher named py, please create proper player as follows.
  # player = gasr.VoicePlayer(voice, python_command="py")
  player = gasr.VoicePlayer(voice)
  player.start()

  interruptible_sleep(3)
  print(f"[ChatGPT {time_str}] ", end='')
  print_incremental(message, 0.05)
  print("\n")

  # Wait finishing Playng the voice.
  player.join()

running = False

# YouTube Video ID and ChatGPT API Key is given from command line in this example.
if len(sys.argv) <= 2:
  exit(0)

# Set params of getting messages from stream source.
stream_params=gasr.streamParams(video_id=sys.argv[1])

# Set params of Chat AI.
ai_params=gasr.aiParams(
  api_key = sys.argv[2],
  system_role = "You are a cheerful assistant who speek English and can get conversation exciting with user.",
  answer_cb = answer_cb
)

# Create GttsVoiceGenerator
# You can choose other language by its 'lang=' argument like 'ja'.
# If you want to change language, Please change the assignment for system role of ai params also.
# The instance isn't necessary for English generator.
voice_generator=gasr.GttsGenerator(lang='en')

# Create GttsAIStreamer instance.
# 'voice_generator=' is omittable for English generator.
ai_streamer =gasr.GttsAIStreamer(
  gasr.params(stream_params=stream_params, ai_params=ai_params, voice_generator=voice_generator)
)

running = True

# Wake up internal thread to get chat messages from stream and play gTTS voices of reading ChatGPT answers aloud.
ai_streamer.start()

# Wait any key inputted from keyboad.
input()

# Turn off runnging flag in order to finish playing gTTS voices of the sample.
running=False

# Finish generating gTTS voices.
# Internal thread will stop soon.
ai_streamer.disconnect()

# terminating internal thread.
ai_streamer.join()

del ai_streamer
